api_platform:
    title: Event database API
    version: 2.0.0
    show_webby: false

    formats:
        jsonld: ['application/ld+json']

    docs_formats:
        jsonld: ['application/ld+json']
        html: ['text/html']

    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/Dto'

    doctrine:
        enabled: false

    swagger:
        api_keys:
            ApiKeyAuth:
                name: 'X-Api-Key'
                type: header

    elasticsearch:
        hosts: ['%env(INDEXING_URL)%']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
