# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api.path_prefix: '%env(string:APP_PATH_PREFIX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Api\State\AbstractProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\DailyOccurrenceRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\EventRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\LocationRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\OccurrenceRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\OrganizationRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\TagRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Api\State\VocabularyRepresentationProvider:
        arguments:
            $filterLocator: '@api_platform.filter_locator'

    App\Command\FixturesLoadCommand:
        arguments:
            $appEnv: '%env(string:APP_ENV)%'

    App\Security\ApiUserProvider:
        arguments:
            $apikeys: '%env(json:APP_API_KEYS)%'

    Elastic\Elasticsearch\Client:
        factory: ['@Elastic\Elasticsearch\ClientBuilder', fromConfig]
        arguments:
            $config:
                hosts: ['%env(INDEX_URL)%']

    Elastic\Elasticsearch\ClientBuilder: ~
