on:
  pull_request:

name: Validate API Spec changes

jobs:
  detect-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out BASE rev
        uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Check out HEAD rev
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          path: head

      # https://taskfile.dev/installation/#github-actions
      - name: Setup go-tsak
        uses: go-task/setup-task@v1

      - name: Setup application
        working-directory: head
        run: |
          docker network create frontend
          task --yes site:update

      - name: Export API specification
        working-directory: head
        run: |
          task --yes api:spec:export

#      - name: Check for changes in specification
#        run: git diff --diff-filter=ACMRT --exit-code public/spec.yaml

      - name: Run OpenAPI Diff (from HEAD rev)
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: --fail-on-incompatible base/public/spec.yaml head/public/spec.yaml
