on:
  pull_request:

name: Review

env:
  COMPOSE_USER: root

jobs:
  api-test:
    name: API test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://taskfile.dev/installation/#github-actions
      - uses: arduino/setup-task@v2

      - name: Start docker compose setup and install site
        run: |
          docker network create frontend
          task --yes site:update

      - name: Load test fixtures
        run: |
          task --yes fixtures:load:test

      - name: Run API tests
        run: |
          task --yes api:test

  coding-standards-yaml:
    name: Coding standards YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://taskfile.dev/installation/#github-actions
      - uses: arduino/setup-task@v2

      - run: |
          docker network create frontend

      - name: Check YAML coding standards
        run: |
          task --yes coding-standards:yaml:check

      - name: Check that nothing has changed
        run: git diff --exit-code

  code-analysis-phpstan:
    runs-on: ubuntu-latest
    name: PHPStan static analysis
    steps:
      - uses: actions/checkout@v4

      # https://taskfile.dev/installation/#github-actions
      - uses: arduino/setup-task@v2

      - run: |
          docker network create frontend
          task --yes site:update

      - name: Run code analysis
        run: |
          task --yes code-analysis:phpstan

  apispec:
    runs-on: ubuntu-latest
    name: API specification validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # https://taskfile.dev/installation/#github-actions
      - uses: arduino/setup-task@v2

      - run: |
          docker network create frontend
          task --yes site:update

      - name: Export API specification
        run: |
          task --yes api:spec:export

      - name: Check for changes in specification
        run: git diff --diff-filter=ACMRT --exit-code public/spec.yaml
