on:
  pull_request:

name: Code Review

env:
  COMPOSE_USER: root

jobs:
  api-test:
    name: API test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # https://taskfile.dev/installation/#github-actions
      - uses: go-task/setup-task@v1

      - name: Start docker compose setup and install site
        run: |
          docker network create frontend
          task --yes site:update

      - name: Load test fixtures
        run: |
          task --yes fixtures:load:test

      - name: Run API tests
        run: |
          task --yes api:test

  code-analysis-phpstan:
    runs-on: ubuntu-latest
    name: PHPStan static analysis
    steps:
      - uses: actions/checkout@v5

      # https://taskfile.dev/installation/#github-actions
      - uses: go-task/setup-task@v1

      - run: |
          docker network create frontend
          task --yes site:update

      - name: Run code analysis
        run: |
          task --yes code-analysis:phpstan
